spring.main.allow-bean-definition-overriding=true
spring.datasource.url=jdbc:sqlite:${DATABASE_PATH:./urlshortener.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.generate-ddl=false
server.port=${SERVER_PORT:8080}
